### ISSUE TITLE
QA report: Geocoding errors

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#100]
Output the subset of the COLP input data where the GRC code is not `00`
Some of these records will be researched by GRU and either they will add the record to PAD or add to a manual corrections file.

**Comment by mgraber** [comment]
@AmandaDoyle Which geocoding step do these errors come from? The call to BL to get the geometry? The call to 1A to check address normalization? Pre-cleaned addresses or raw addresses?

**Comment by AmandaDoyle** [comment]
Table schema

`dcas_bbl
1a_bbl
1a_bill_bbl
dcas_hnum
dcas_sname
normalized_hnum
normalized_sname
1a_grc
1a_rsn
1a_msg
agency
usecode
usetype
category,
expandcat
excatdesc
leased
finalcom
agreement`
