### ISSUE TITLE
Geocoding/mapping: Map air rights lots to the X,Y of the donating BBL

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#103]
Map air rights lots to the X,Y of the donating BBL – use air rights table from DTM 

We'll work with AF to get the air rights table into his regular DTM package.

Initial draft logic
1) After existing geocoding methods select lots that do not have a geometry
2) Use the lookup to match the IPIS BBL to the AIR_RIGHTS_BBL to get the DONATING_BBL
3) Join the DONATING_BBL to the BBL in the DTM (I wonder if joining to PLUTO would get the same result?) to get the geometry and apply this to the COLP record

**Comment by mgraber** [comment]
@AmandaDoyle should we be identifying records that need to get BBL from the air rights table using missing geom, or by identifying lots that start with a 9?

**Comment by mgraber** [comment]
In geocode.py, inputs are currently:
```sql
SELECT DISTINCT bbl
                        from dcas_ipis
```

We geocode the donating BBLs in this step, too:
```sql
SELECT DISTINCT bbl
       FROM dcas_ipis
UNION
SELECT DISTINCT donating_bbl
       FROM dcas_ipis a
       LEFT JOIN air_rights b
       ON a.bbl = b.air_rights_bbl
```

Then

**Comment by AmandaDoyle** [comment]
> @AmandaDoyle should we be identifying records that need to get BBL from the air rights table using missing geom, or by identifying lots that start with a 9?

Yes, I think so.  It looks like most BBLs where the lots start with 9 do not geocode, but one does in the current version of COLP (BBL = 2024209039) and it's located in the roadbed.  The logic would need to be something like this `WHERE lot LIKE '9%' and LENGTH(lot::text) = 4` OR `WHERE RIGHT(bbl, 4) LIKE '9%') to get the right subset.  

@lseirup can you confirm that all Air Rights lots have a lot starting with 9?
