### ISSUE TITLE
Geocoding/mapping: Change how records are geocoded with GeoSupport

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#104]
Current process:
- Run BBL from input data through BL to get address
- Take address returned by BL through 1A and 1B.  If there is a hit in 1A and 1B take these values, otherwise take values returned by BL

New process:
- Run BBL from input data through BL 
- Take values from BL
- Join on PLUTO to get CD

Where geographic attributes come from
- BBL = from DCAS
- Address = normalized address from DCAS
- Lat/Long = GeoSupport BL

**Comment by mgraber** [comment]
**Community District**

In our current process, CD comes primarily from the source data, and gets backfilled with PLUTO:
https://github.com/NYCPlanning/db-colp/blob/eaf85ac39c3d2cc1e3c4fc0a0c12c69970487768/colp_build/sql/create_colp.sql#L99-L104
then 
https://github.com/NYCPlanning/db-colp/blob/eaf85ac39c3d2cc1e3c4fc0a0c12c69970487768/colp_build/sql/create_colp.sql#L176-L186

**Normalized address**
The process of normalizing addresses involves python text parsing and Geosupport normalization.
1) Run DCAS house number and street name through a python normalization function to correct for things like white-space, special characters, house numbers of zero or "bed of"
https://github.com/NYCPlanning/db-colp/blob/eaf85ac39c3d2cc1e3c4fc0a0c12c69970487768/colp_build/python/normalize_addresses.py#L24-L39

2) Run this pre-cleaned address through 1A to get normalized address
