### ISSUE TITLE
QAQC Master Issue

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-colp#107]
## dcas_ipis_geoerrors #100
Contains `dcas_ipis` records that correspond with a `dcas_ipis_geocodes` record where the field `grc <> 00`.
This means that the BBL from the input data either did not successfully get coordinates from function BL, or got results with a warning (`grc = 01`).

### Schema
name | source
----- | -------
bbl | dcas_ipis
house_number | dcas_ipis
street_name | dcas_ipis
alternate_address | dcas_ipis
parcel_name | dcas_ipis
agency | dcas_ipis
primary_use_code | dcas_ipis
primary_use_text | dcas_ipis
owner | dcas_ipis
owned/leased | dcas_ipis
geo_bbl | dcas_ipis_geocodes (BL)
bill_bbl | dcas_ipis_geocodes (BL)
latitude | dcas_ipis_geocodes (BL)
longitude | dcas_ipis_geocodes (BL)
x_coord | dcas_ipis_geocodes (BL)
y_coord | dcas_ipis_geocodes (BL)
grc | dcas_ipis_geocodes (BL)
rsn | dcas_ipis_geocodes (BL)
msg | dcas_ipis_geocodes (BL)
wkb_geometry | dcas_ipis_geocodes (BL)

## dcas_ipis_unmapped #97
Contains `dcas_ipis records` that correspond with a `_colp` record missing a geometry. This is a subset of `dcas_ipis_geoerrors`
This means that the BBL from the input data did not successfully get coordinates from function BL.

### Schema:
name | source
----- | -------
bbl | dcas_ipis
house_number | dcas_ipis
street_name | dcas_ipis
alternate_address | dcas_ipis
parcel_name | dcas_ipis
agency | dcas_ipis
primary_use_code | dcas_ipis
primary_use_text | dcas_ipis
owner | dcas_ipis
owned/leased | dcas_ipis
geo_bbl | dcas_ipis_geocodes (BL)
bill_bbl | dcas_ipis_geocodes (BL)
grc | dcas_ipis_geocodes (BL)
rsn | dcas_ipis_geocodes (BL)
msg | dcas_ipis_geocodes (BL)

## address_comparison #106 
Contains house number and street name as included in `dcas_ipis`, house number and street name as returned from python-based normalization (string-pattern cleaning then running through function N), and the results of running both sets of house number and street names through function 1A.

### Schema
name | source
----- | -----
dcas_bbl | dcas_ipis
dcas_hnum | dcas_ipis
norm_hnum | Results of python cleaning and function N
dcas_sname | dcas_ipis
norm_sname | Results of python cleaning and function N
dcas_geo_bbl | Results of running dcas_hnum and dcas_sname through 1A
norm_geo_bbl | Results of running norm_hnum and norm_sname through 1A
dcas_bill_bbl | Results of running dcas_hnum and dcas_sname through 1A
norm_bill_bbl | Results of running norm_hnum and norm_sname through 1A
dcas_grc | Results of running dcas_hnum and dcas_sname through 1A
norm_grc | Results of running norm_hnum and norm_sname through 1A
dcas_rsn | Results of running dcas_hnum and dcas_sname through 1A
norm_rsn | Results of running norm_hnum and norm_sname through 1A
dcas_msg | Results of running dcas_hnum and dcas_sname through 1A
norm_msg | Results of running norm_hnum and norm_sname through 1A
agency | _colp
usecode | _colp
usetype | _colp
ownership | _colp
category | _colp
expandcat | _colp
excatdesc | _colp
leased | _colp
finalcom | _colp
agreement | _colp

## address_bbl_mismatch #98 
Contains records from `dcas_ipis` where the BBL returned by running a normalized address through 1A differs from the source bbl. These records are ones where `dcas_bbl <> norm_geo_bbl` in `address_comparison` .

## usetype_changes #102
Contains counts of the number of records per use type over multiple versions of colp.

### Schema

name | source
----- | ------
usetype | colp
num_records | colp

**Comment by AmandaDoyle** [comment]
New tables

## ipis_unmapped #97
Contains `dcas_ipis records` that correspond with a `_colp` record missing a geometry.
This means that the BBL from the input data did not successfully get coordinates from function BL.

### Schema
name | source
----- | -------
bbl | dcas_ipis
house_number | dcas_ipis
street_name | dcas_ipis
alternate_address | dcas_ipis
parcel_name | dcas_ipis
agency | dcas_ipis
primary_use_code | dcas_ipis
primary_use_text | dcas_ipis
owner | dcas_ipis
owned/leased | dcas_ipis

## usetype_changes #102
Contains counts of the number of records per use type over multiple versions of colp.

### Schema

name | source
----- | ------
usetype | colp
num_records_current | colp current version
num_records_previous | colp previous version
difference | = num_records_current - num_records_previous

## ipis_colp_geoerrors #100
The purpose of this table is to report address errors to DCAS or GRU for correction or research.
Contains house number and street name as included in `dcas_ipis`, house number and street name as returned from python-based normalization (string-pattern cleaning then running through function N), and the results of running both sets of house number and street names through function 1B.

From this table we will parse out:
- records for GRU to research, such as records where the grc code is 41 or 42 for certain types of use codes that have buildings
- invalid addresses for the BBL to report to DCAS.  We'll need to figure out how to make sure we're accounting for condo and billing bbl differences. 

### Schema
name | source
----- | -----
dcas_bbl | dcas_ipis
dcas_hnum | dcas_ipis
norm_hnum | Results of python cleaning and function N
dcas_sname | dcas_ipis
norm_sname | Results of python cleaning and function N
dcas_geo_bbl | Results of running dcas_hnum and dcas_sname through 1A
norm_geo_bbl | Results of running norm_hnum and norm_sname through 1A
dcas_bill_bbl | Results of running dcas_hnum and dcas_sname through 1A
norm_bill_bbl | Results of running norm_hnum and norm_sname through 1A
dcas_grc_1a | Results of running dcas_hnum and dcas_sname through 1B
norm_grc_1a | Results of running norm_hnum and norm_sname through 1B
dcas_rsn_1a | Results of running dcas_hnum and dcas_sname through 1B
norm_rsn_1a | Results of running norm_hnum and norm_sname through 1B
dcas_msg_1a | Results of running dcas_hnum and dcas_sname through 1B
norm_msg_1a | Results of running norm_hnum and norm_sname through 1B
dcas_grc_1e | Results of running dcas_hnum and dcas_sname through 1B
norm_grc_1e | Results of running norm_hnum and norm_sname through 1B
dcas_rsn_1e | Results of running dcas_hnum and dcas_sname through 1B
norm_rsn_1e | Results of running norm_hnum and norm_sname through 1B
dcas_msg_1e | Results of running dcas_hnum and dcas_sname through 1B
norm_msg_1e | Results of running norm_hnum and norm_sname through 1B
agency | _colp
usecode | _colp
usetype | _colp
ownership | _colp
category | _colp
expandcat | _colp
excatdesc | _colp
leased | _colp
finalcom | _colp
agreement | _colp
