### ISSUE TITLE
Add QAQC table of name normalization changes

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#122]
Output a table for QAQC containing the following fields:
- bbl
- original parcel name - the parcel name value before changing
- normalized parcel name - the parcel name value after applying regex and replace logic
- reviewed - a boolean flag indicating if the records has been reviewed
An easy way to do this might be to join on COLP to the IPIS data and select records where parcel name has been changed.  
This will be a living table.  The intent is to have someone manually review all the parcel name changes, and with each update only review new changes.  If the reviewed does not agree with a parcel name change they will add it as a correction to the manual research table.

We can discuss workflow and implementation before diving into code.

**Comment by mgraber** [comment]
Is this a modification of the table `ipis_modified_names`, or an entirely new table?
https://github.com/NYCPlanning/db-colp/blob/f04959af30c5a1ebff51b48d53a1bbae26dd861e/colp_build/sql/export_qaqc.sql#L57-L74

**Comment by AmandaDoyle** [comment]
Yes, this is as simple as adding the `reviewed` - boolean flag to the existing table
