### ISSUE TITLE
Update logic of assigning geometries to air rights lots

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#146]
1) ignore 89 lots 2) if one bbl gets gets a geom but others don't we want to get the record with a geometry, and 3) if two or more bbls get a geom then add logic to force consistency.

**Comment by lseirup** [comment]
For #3, if there are two or more donating BBLs for an air rights lot, use the donating BBL whose number is the same as the air rights lot with the 9 removed, e.g., for 1009999062, use 1009990062, not 1009990061
