### ISSUE TITLE
ipis_modified_names contains duplicate records

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/db-colp#147]
There are > 900 duplicates in the file

**Comment by mgraber** [comment]
If a name modification is the same for multiple addresses, BBLs, or agencies, do we include multiple records in `ipis_modified_names`?
+ Number of records when selecting distinct on dcas_bbl, dcas_hnum, display_hnum, dcas_sname, sname_1b, parcel_name, display_name, agency, primary_use_code, and primary_use_text: 1919
+ Number of records when selecting distinct on dcas_bbl, parcel_name, display_name, agency, primary_use_code, and primary_use_text: 1919
+ Number of records when selecting distinct on dcas_hnum, display_hnum, dcas_sname, sname_1b, parcel_name, display_name, agency, primary_use_code, and primary_use_text: 1861
+ Number of records when selecting distinct on parcel_name, display_name, agency, primary_use_code, and primary_use_text: 1556
+ Number of records when selecting distinct on parcel_name, display_name, and agency: 1518
+ Number of records when selecting distinct on parcel_name, display_name, primary_use_code, and primary_use_text: 1499
+ Number of records when selecting distinct on parcel_name, and display_name: 1157

**Comment by lseirup** [comment]
@mgraber Only remove duplicate records that have the same value for all fields shown in the report. When I deduplified using Excel, I got 1919 records.
