### ISSUE TITLE
Fix ownership mapping from IPIS

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-colp#15]
Current mapping takes "owner" field directly from IPIS, which contains C, O, M, or null.
Target schema's "ownership" field contains Q, X, P, or null.
How do these map, if at all?

**Comment by AmandaDoyle** [comment]
Based on my analysis, currently the mapping is:
owner     ownership count
C	        NULL	31854
NULL	P	        6291
O	        Q	        2885
M	        X	        316

It's worth asking @lseirup if we should continue to use the current ownership codes of P,Q,X and add C per DCAS' request or should we adopt the codes from IPIS and add P where the owner code is NULL?

**Comment by AmandaDoyle** [comment]
Decision: Use IPIS values and where and IPIS value is NULL replace it with "P"
