### ISSUE TITLE
There are COLP records with a NULL CD value, but PLUTO has a CD value

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#172]
If I query in Carto I get 105 records where COLP has a NULL CD value but PLUTO has a CD value
`SELECT * FROM dcpadmin.colp_1 where cd is null and mapbbl IN (SELECT bbl from dcp_mappluto where cd is not null)`

**Comment by SPTKL** [comment]
@AmandaDoyle 
Mapbbl is a combination of billing bbl and bbl
https://github.com/NYCPlanning/db-colp/blob/8b7042ebe6a2884edba612518f3c8e1842f3fc84/sql/create_colp.sql#L104-L109

we are using the donating bbl for the cd join, should we switch to mapbbl for the pluto join?
https://github.com/NYCPlanning/db-colp/blob/8b7042ebe6a2884edba612518f3c8e1842f3fc84/sql/create_colp.sql#L187-L195

**Comment by AmandaDoyle** [comment]
> we are using the donating bbl for the cd join, should we switch to mapbbl for the pluto join?
Yes, let's change the join to PLUTO to get the CD to use the mapbbl
