### ISSUE TITLE
Incorporate DCAS modified parcel names into COLP

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#183]
Incorporate DCAS modified parcel names into COLP
Make sure that they are pulled from IPIS, modified from what's attached, and not automatically altered.

[DCAS Review of DCP Parcel Name Modifications.xlsx](https://github.com/NYCPlanning/db-colp/files/6779141/DCAS.Review.of.DCP.Parcel.Name.Modifications.xlsx)

**Comment by SPTKL** [comment]
modifying logic for the text matching
https://github.com/NYCPlanning/db-colp/blob/main/sql/clean_parcelname.sql
this would be another input dataset (combine Lynn's review and DCAS' review)

**Comment by AmandaDoyle** [comment]
@lseirup Here is the issue about incorporating DCAS modified parcel names into COLP.  The first comment contains the file.
