### ISSUE TITLE
Split export and upload steps

### ISSUE THREAD

**Issue by SashaWeinstein** [NYCPlanning/db-colp#194]
I just accidentally uploaded my local build to the latest folder on edm-publishing because I didn't realize the export and upload steps were combined. These steps should be split and upload shouldn't overwrite latest on default. We made this same change to pluto and I think it was a good improvement

**Comment by AmandaDoyle** [comment]
Yes - let's go ahead and make this improvement to avoid this in the future.

**Comment by SashaWeinstein** [comment]
@AmandaDoyle I think it would be good to move COLP in line with other data products and upload to folders named after the branch the code is run from, and have our typical date+latest folders inside these branch folders. I want to ask before implementing this change though
