### ISSUE TITLE
corrections not being applied 

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-colp#198]
corrections in the build step not applied.

**Comment by SashaWeinstein** [comment]
# Possible Fix: switch corrections from by-record to by-value

## Old Process
Currently the corrections are applied on a by-record basis. By this I mean that each correction is associated with a single value in a single record. (There may be a better technical term for this but I don't know what it is). This is implemented with a modifications table where each row in the table is a single record/field combination, with an old value to take out and a new value to take in. This would be a working implementation if we had a way to consistently identify city owned and leased properties from one version to the next. Unfortunately our current system of assigning unique keys with the `uid` column is specific to an individual build, and the modifications table needs to work for all builds. 

## Suggested Upgrade
Te and I think we should move to a "by-value" system of recoding, where all records with a particular value for a given field are recoded as a group based on a single old value -> new value mapping. The first thing to point out is that the existing mapping already essentially works this way. When we ran this query on the modifications table
```sql
SELECT old_value, old_value||'  -> ' ||new_value, count(*) FROM modifications GROUP BY old_value, new_value ORDER BY old_value
```
we saw multiple occurrences of the same old value -> new value mapping, and no instances of an old value being mapped to two different new values across different records. 
So this upgrade would simplify the existing logic without changing the output. 

It's also important to recognize that we don't have sufficient information to keep a by-record corrections implementation consistent from build to build. An approach of just changing the uid's in the modifications table involves guessing which records in the new COLP "match" records from the previous version.

So the new modifications table should have no `uid` column and rows with duplicate old value -> new value mappings can be deleted. For example 14 rows map `RUTH B. GINSBURG BROOKLYN MUNI BLDG` -> `RUTH BADER GINSBURG BROOKLYN MUNICIPAL BUILDING`, but we only need the correction in there one time. The `_procedures.sql` will also have to be upgraded as well. 

If we want a by-record system of corrections that would take a bunch more work to uniquely identify city owned and leased properties.

**Comment by AmandaDoyle** [comment]
Thanks for writing this up.  Please see how PLUTO applies corrections.  I think that there needs to be a 2 step corrections process in COLP, one where the UID is taken into account and another where the UID is not taken into account when applying a correction.  What you describe above is NOT taking the UID into account, which I think is 100% appropriate for applying corrections to the `PARCELNAME` field and likely appropriate for `SNAME`; however, I am not 100% sure that this is appropriate for the `AGREEMENT` field (i.e. do we want all "S" values to be NULL?  I don't think so, so we need to find the records where we want S to be NULL for Agreement and update the UID).

**Comment by SashaWeinstein** [comment]
Ah ok cool. Conceptually what's the deal with the S values? I assumed they should all be sent to None, figured they were erroneous values. But I see now that all `AGREEMENT` values are L, S, and M

**Comment by AmandaDoyle** [comment]
Nope, "S" is a real value and there are some City Owned and Leased properties where that value is incorrect from the source data and needs to be corrected.

**Comment by AmandaDoyle** [comment]
@SashaWeinstein  yes, that's exactly right.
