### ISSUE TITLE
Update links in ReadMe to point to main/latest in DO

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#201]
The DO file paths need to be updated for the files available for download in the [ReadMe](https://github.com/NYCPlanning/db-colp#outputs) to main/latest/etc

**Comment by td928** [comment]
So the breaking of these links to now the upload function has the branch before the space names. Could be fixed by adding main to all url links or change our upload function to remove the branch name the github actions were run out of.
