### ISSUE TITLE
Normalize DCAS provided addresses 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#47]
Provide DCAS raw address, DCAS normalized address, and geosupport address from BL function in single output for research purposes so that we can decide what address to show in COLP

Run DCAS address through function 1L and N to get normalized street number and street name.

LS will then decide what address to show in COLP

**Comment by mgraber** [comment]
Initial normalization included in #50.
Further house-number normalization (to better match 1L) could include:
+ Borough-specific parsing of hyphens
+ Retaining spaces between base number and suffix
