### ISSUE TITLE
Finalcom is "D" for all values

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#60]
finalcom is "D" for all values
Based on the logic
https://github.com/NYCPlanning/db-colp/blob/646f406a9ba006b54750a8672de586f56aa49729/colp_build/sql/create_colp.sql#L118 
and this query
`SELECT a.bbl, finalcom, u_f_use_code FROM dcas_ipis a, colp b WHERE a.bbl = b.bbl;`
`finalcom` should only = "D" if 'u_f_use_code' IS NOT NULL

**Comment by mgraber** [comment]
Logic is not working appropriately because u_f_use_codes are '' and not NULL
