### ISSUE TITLE
Add expandcatdesc field

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-colp#68]
expandcatdesc add as field to COLP with values for expandcat values (like usetype)

**Comment by mgraber** [comment]
@AmandaDoyle these values?

```
Expanded categories are:
        -- 1: Offices
        -- 2: Educational facilities
        -- 3: Recreational & cultural facilities, cemetaries
        -- 4: Public safety and judicial
        -- 5: Health & social services
        -- 6: Tenented & retail
        -- 7: Transportation & infrastructure
        -- 8: Not in use
        -- 9: In use residential
        -- NULL: Dispositions and other final commitments
```

**Comment by AmandaDoyle** [comment]
[COLP_2018 13.xlsx](https://github.com/NYCPlanning/db-colp/files/5452267/COLP_2018.13.xlsx)
The `Use Code` tab has the lookup between the expanded category code and the expanded category description.

What about `excatdesc` or `expandcatd`?

This field should go right after `expandcat`
