### ISSUE TITLE
Change field datatypes to match PLUTO

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-colp#70]
- make bbl, billbbl double
- make lat/ long fields and xcoords and ycoords double
- block and lot, cd are numeric

**Comment by mgraber** [comment]
@AmandaDoyle Are these the datatypes requested for the shapefile? Double isn't a postgres type.

**Comment by SPTKL** [comment]
I think so, we might need something like the export script for PLUTO, it's also a good place to cap all the field names
https://github.com/NYCPlanning/db-pluto/blob/master/pluto_build/sql/export.sql

**Comment by mgraber** [comment]
So double fields should get cast as `::numeric(10,0)`?

**Comment by SPTKL** [comment]
shapefile double -> numeric(19,8), 
shapefile integer -> numeric(10,0)
shapefile smallint/short -> numeric(5,0)

**Comment by AmandaDoyle** [comment]
Yes, LS is looking to have the data types in the shapefile to match across data products
