### ISSUE TITLE
Parse addresses & geocode

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-colp#8]
Geocode based primarily on `parcel_address` field. Note that addresses are missing for about 12% of the input data.

Addresses are points, place names, or street names. Street names frequently include 'BED OF' as a prefix.
Street names are also frequently missing a suffix, or have incomplete suffixes.

Examples:
-  'BED OF HARLEM RIVER DRIVE' 
-  'BED OF HARLEM RIVER' 
-  'CROSS BAY BOULE'

**Comment by SPTKL** [comment]
why don't we geocode using bbl

**Comment by SPTKL** [comment]
### geocode stats: 
+ total records: 15932
+ no address: 6936 (43%)
+ no coordinates: 828 (5%)

**Comment by mgraber** [comment]
Note that future input data will likely have hnum and street as separate fields (see #14)

**Comment by mgraber** [comment]
538 out of 17049 of the input records do not have a house number (roughly 3%).
