### ISSUE TITLE
QA report DCAS: lots that are not mapped

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-colp#97]
Output the subset of the COLP input data that is not have a geometry to send to DCAS

**Comment by mgraber** [comment]
@AmandaDoyle Is this different than the output of COLP records without geometries? We create that here:

https://github.com/NYCPlanning/db-colp/blob/eaf85ac39c3d2cc1e3c4fc0a0c12c69970487768/colp_build/sql/_export.sql#L14-L26

**Comment by AmandaDoyle** [comment]
@mgraber Yes, the change is to include the fields from the input data, and not the COLP records.
